
package com.iglesia.matrimonios;

import java.awt.Dimension;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import java.time.format.DateTimeFormatter;
import java.time.LocalDateTime;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.ViewportLayout;
import javax.swing.border.EmptyBorder;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;


public class gui_Matrimonio_Visualiza_Datos extends javax.swing.JFrame {

    /**
     * Creates new form JFrameConsulta
     */
    public gui_Matrimonio_Visualiza_Datos() {
        initComponents();
    
        setTitle("Datos de Repositorio de Matrimonios");
        JTabla.setModel( new DefaultTableModel() );
        JTabla.setAlignmentX(TOP_ALIGNMENT);
        JTabla.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        
        //JTabla.setSize(2300, 700);
        this.setPreferredSize(new Dimension(2200, 700));
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        
        this.pack();
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tConsulta = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTabla = new javax.swing.JTable();
        consulta = new javax.swing.JButton();
        consultaTodos = new javax.swing.JButton();
        LImpiar = new javax.swing.JButton();
        Salir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 255));
        jLabel1.setText("BUSCAR POR");

        tConsulta.setName("tConsulta"); // NOI18N

        JTabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8", "Title 9", "Title 10", "Title 11", "Title 12", "Title 13", "Title 14", "Title 15", "Title 16", "Title 17", "Title 18", "Title 19", "Title 20"
            }
        ));
        JTabla.setAlignmentY(10.0F);
        jScrollPane1.setViewportView(JTabla);

        consulta.setText("Consulta por Parametro");
        consulta.setName("consulta"); // NOI18N
        consulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultaActionPerformed(evt);
            }
        });

        consultaTodos.setText("Consulta");
        consultaTodos.setName("consulta"); // NOI18N
        consultaTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultaTodosActionPerformed(evt);
            }
        });

        LImpiar.setText("Limpiar");
        LImpiar.setName("consulta"); // NOI18N
        LImpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LImpiarActionPerformed(evt);
            }
        });

        Salir.setText("Salir");
        Salir.setName("consulta"); // NOI18N
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(consulta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(consultaTodos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LImpiar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Salir)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(consulta)
                    .addComponent(consultaTodos)
                    .addComponent(LImpiar)
                    .addComponent(Salir))
                .addGap(40, 40, 40)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 601, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // No lo usamos
    // public void get_data(){
    
    //   String [] columnas = { "Nombre", "Fecha Bautizo", "Sacerdote", "Lugar Nacimiento", 
    //              "Fecha Nacimiento", "Papa", "Mama", "Padrino", "Madrina", 
    //              "RC Año", "Tomo", "Folio", "Acta", "Fecha", "# Inscripcion", 
    //              "RP Libro", "Pagina", "Numero", "Novedades"} ; 
       
    //   DefaultTableModel modelo = new DefaultTableModel(null, columnas);
    //   JTabla.getColumnModel().getColumn(0).setMaxWidth(200);
    //   JTabla.setModel(modelo);
        
    //}
    
    public void llena_JTable(int tipo_consulta){
      
        Connection cnt = null;  
        //PreparedStatement pst = null;
        Statement st = null;
        ResultSet rs = null;
        
        try {
        
        String condicion = tConsulta.getText();
        cnt = obtiene_conexion();
        String sql = "select fecha_matri, nombre_sacerdote, proclamas, "
                + " nombre_novio, nombre_papa_novio, nombre_mama_novio,"
                + " nombre_novia, nombre_papa_novia, nombre_mama_novia, "
                + " nombre_testigos, rc_lugar, rc_año, rc_tomo, rc_acta, "
                + " nota_marginal, legitimacion_de_hijos, rp_folio, "
                + " rp_numero, rp_libro, novedades " 
                + " from matrimonios ";
        if (tipo_consulta == 0)
            sql += " where nombre_novio like '%" + condicion + "%'";
        st = cnt.createStatement();
        rs = st.executeQuery(sql);
        
        ResultSetMetaData rsmd = rs.getMetaData();
        DefaultTableModel model =  (DefaultTableModel) JTabla.getModel();
        int cols = rsmd.getColumnCount();
        String[] arr_columns = new String[cols];  
        for (int i =0; i<cols; i++)
          arr_columns[i] = rsmd.getColumnName(i+1);
        System.out.println(arr_columns[0]);
        arr_columns[0]="Fecha Matrimonio"; arr_columns[1]="Nombre Sacerdote"; arr_columns[2]="Proclamas";
        arr_columns[3]="Nombre Novio"; arr_columns[4]="Nombre Papa Novio"; arr_columns[5]="Nombre Mama Novio";
        arr_columns[6]="Nombre Novia"; arr_columns[7]="Nombre Papa Novia"; arr_columns[8]="Nombre Mama Novia";
        arr_columns[9]="Nombre Testigos"; arr_columns[10]="RC Lugar"; arr_columns[11]="Rc Año";
        arr_columns[12]="Rc Tomo"; arr_columns[13]="Rc Acta"; arr_columns[14]="Nota Marginal";
        arr_columns[15]="Legitimacion de Hijos"; arr_columns[16]="Rp Folio"; arr_columns[17]="Rp Numero"; 
        arr_columns[18]="Rp Libro"; arr_columns[19]="Novedades";
        
        model.setColumnIdentifiers(arr_columns);
        
        // Poniendo ancho a las columnas
        //JTabla.getColumnModel().getColumn(0).setMaxWidth(250);
        JTabla.getColumnModel().getColumn(0).setPreferredWidth(150);
        JTabla.getColumnModel().getColumn(1).setPreferredWidth(200);
        JTabla.getColumnModel().getColumn(2).setPreferredWidth(100);
        JTabla.getColumnModel().getColumn(3).setPreferredWidth(200);
        JTabla.getColumnModel().getColumn(4).setPreferredWidth(200);
        JTabla.getColumnModel().getColumn(5).setPreferredWidth(200);
        JTabla.getColumnModel().getColumn(6).setPreferredWidth(200);
        JTabla.getColumnModel().getColumn(7).setPreferredWidth(200);
        JTabla.getColumnModel().getColumn(8).setPreferredWidth(200);
        JTabla.getColumnModel().getColumn(9).setPreferredWidth(200);
        JTabla.getColumnModel().getColumn(10).setPreferredWidth(100);
        JTabla.getColumnModel().getColumn(11).setPreferredWidth(100);
        JTabla.getColumnModel().getColumn(12).setPreferredWidth(100);
        JTabla.getColumnModel().getColumn(13).setPreferredWidth(100);
        JTabla.getColumnModel().getColumn(14).setPreferredWidth(200);
        JTabla.getColumnModel().getColumn(15).setPreferredWidth(200);
        JTabla.getColumnModel().getColumn(16).setPreferredWidth(100);
        JTabla.getColumnModel().getColumn(17).setPreferredWidth(100);
        JTabla.getColumnModel().getColumn(18).setPreferredWidth(100);
        JTabla.getColumnModel().getColumn(19).setPreferredWidth(300); // 3200
        
        DateFormat dateFormat = null;
        dateFormat = new SimpleDateFormat("dd/MM/yyyy");
        
        String strDate = null;
        String campo1 = null; String campo2= null; String campo3 = null; String campo4 = null;
        String campo5 = null; String campo6= null; String campo7 = null; String campo8 = null;
        String campo9 = null; String campo10= null; String campo11 = null; String campo12 = null;
        String campo13 = null; String campo14 = null; String campo15 = null; 
        String campo16 = null; String campo17 = null; String campo18 = null; String campo19 = null;
        String campo20 = null;
        
        while (rs.next()) {                
                
                campo1 = dateFormat.format(rs.getDate("fecha_matri") );
                campo2 = rs.getString("nombre_sacerdote");
                campo3 = rs.getString("proclamas");
                campo4 = rs.getString("nombre_novio");
                campo5 = rs.getString("nombre_papa_novio");
                campo6 = rs.getString("nombre_mama_novio");
                campo7 = rs.getString("nombre_novia");
                campo8 = rs.getString("nombre_papa_novia");
                campo9 = rs.getString("nombre_mama_novia");
                campo10 = rs.getString("nombre_testigos");
                campo11 = rs.getString("rc_lugar");
                campo12 = rs.getString("rc_año");
                campo13 = rs.getString("rc_tomo");
                campo14 = rs.getString("rc_acta");
                campo15 = rs.getString("nota_marginal");
                campo16 = rs.getString("legitimacion_de_hijos");
                campo17 = rs.getString("rp_folio");
                campo18 = rs.getString("rp_numero");
                campo19 = rs.getString("rp_libro");
                campo20 = rs.getString("novedades");
                
                
                String[] row = { campo1, campo2, campo3, campo4, campo5, 
                                 campo6, campo7, campo8, campo9, campo10, 
                                 campo11, campo12, campo13, campo14, campo15, 
                                 campo16, campo17, campo18, campo19, campo20 }; 
                model.addRow( row );
            }
        
        }
        
        catch(SQLException e) {
                System.out.println("error tipo SQLException " + e.getMessage() );
                JOptionPane.showMessageDialog(null, "Error SQLException" + e.getMessage());
       }
        catch(Exception e){
                System.out.println("error tipo Exception " + e.getMessage() );
                JOptionPane.showMessageDialog(null, "Error Exception" + e.getMessage());
        } 
        finally{
                try {   if (cnt != null)   cnt.close();
                        if (st != null)    st.close();
                        if (rs != null)    rs.close();}
                catch(SQLException sq){
                    System.out.println("En Finally cerrando conexion en funcion llena_JTable" + sq.getMessage() );
                    JOptionPane.showMessageDialog(null, "En Finally cerrando conexion, en funcion llena_JTable " + sq.getMessage() );
                }
        }
        
        setVisible(true);
        //setSize(1000, 600);
        
    }
    
    public Connection obtiene_conexion(){
        Connection con= null;
        try {                 // OJO Cambiar base y password 
            String url = "jdbc:MySQL://localhost:3306/sacramentos";  
            String user = "root";
            String password = "";
            Class.forName("com.mysql.cj.jdbc.Driver");
            //System.out.println("error tipo A ");
            con = (Connection) DriverManager.getConnection(url,user,password);
            
        }            
        catch(SQLException e) {
                System.out.println("error SQLException " + e.getMessage() );
                JOptionPane.showMessageDialog(null, "Error SqlException en Obtiene Conexion " + e.getMessage());
            }
        catch(Exception e){
                System.out.println("error Exception " + e.getMessage() );
                JOptionPane.showMessageDialog(null, "Error Exception en Obtiene Conexion" + e.getMessage() );
            } 
        return con;
    }
    
    private void consultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultaActionPerformed
        //get_data();
        llena_JTable(0);
    }//GEN-LAST:event_consultaActionPerformed

    private void consultaTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultaTodosActionPerformed
        llena_JTable(1);
    }//GEN-LAST:event_consultaTodosActionPerformed

    private void LImpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LImpiarActionPerformed
        JTabla.setModel( new DefaultTableModel() );
        tConsulta.setText("");
    }//GEN-LAST:event_LImpiarActionPerformed

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_SalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(gui_Matrimonio_Visualiza_Datos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(gui_Matrimonio_Visualiza_Datos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(gui_Matrimonio_Visualiza_Datos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(gui_Matrimonio_Visualiza_Datos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new gui_Matrimonio_Visualiza_Datos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable JTabla;
    private javax.swing.JButton LImpiar;
    private javax.swing.JButton Salir;
    private javax.swing.JButton consulta;
    private javax.swing.JButton consultaTodos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField tConsulta;
    // End of variables declaration//GEN-END:variables
}
