package com.iglesia.matrimonios;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import java.time.format.DateTimeFormatter;
import java.time.LocalDateTime;

public class gui_Matri_Frame extends javax.swing.JFrame {

    /**
     * Creates new form gui_Matri_Frame
     */
    public gui_Matri_Frame() {
        initComponents();
        llena_combo();
        
        tf_rc_lugar.setText("Guayaquil");
        setea_Fecha_actual(tf_fecha);
        this.setLocationRelativeTo(null);
    }
    public void setea_Fecha_actual(JTextField campo){ 
         DateTimeFormatter dtf = DateTimeFormatter.ofPattern("dd/MM/yyyy");
         campo.setText( dtf.format(LocalDateTime.now()) );
    }
    public void llena_combo(){
      Connection cnt = null;    
      Statement stm = null;
      ResultSet rs = null;
      try
        {    
            cnt = obtiene_conexion();
            stm = cnt.createStatement();
            String sql = "select * from opciones_autoridades";
            rs = stm.executeQuery(sql);
            while ( rs.next() ){
              String str =  rs.getString("nom_opc_autoridad");
              lis_autoridad.removeAll();
              lis_autoridad.addItem(str);
            }
      
        }
        catch(SQLException e) {
                //System.out.println("error tipo SQLException " + e.getMessage() );
                JOptionPane.showMessageDialog(null, "Error SQLException en funcion llena_combo " + e.getMessage());
        }
        catch(Exception e){
                //System.out.println("error tipo Exception " + e.getMessage() );
                JOptionPane.showMessageDialog(null, "Error Exception en funcion llena_combo " + e.getMessage());
        } 
        finally{
                try {   if (cnt != null)   cnt.close();  
                        if (stm != null)   stm.close();
                        if (rs != null)    rs.close(); }
                catch(SQLException sq){
                    //System.out.println("En Finally cerrando conexion en funcion llena_combo" + sq.getMessage() );
                    JOptionPane.showMessageDialog(null, "En Finally, en funcion llena_combo " + sq.getMessage() );
                }
        }
    }
    public Connection obtiene_conexion(){
        Connection con= null;
        try {
            String url = "jdbc:MySQL://localhost:3306/sacramentos";         //db is the name of the database
            String user = "root";
            String password = "";
            Class.forName("com.mysql.cj.jdbc.Driver");
            //System.out.println("error tipo A ");
            con = (Connection) DriverManager.getConnection(url,user,password);
            
        }            
        catch(SQLException e) {
                System.out.println("error SQLException " + e.getMessage() );
                JOptionPane.showMessageDialog(null, "Error SqlException en Obtiene Conexion " + e.getMessage());
            }
        catch(Exception e){
                System.out.println("error Exception " + e.getMessage() );
                JOptionPane.showMessageDialog(null, "Error Exception en Obtiene Conexion" + e.getMessage() );
            } 
        return con;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        lab2 = new javax.swing.JLabel();
        tf_fecha = new javax.swing.JTextField();
        lab3 = new javax.swing.JLabel();
        tf_sacerdote = new javax.swing.JTextField();
        lab4 = new javax.swing.JLabel();
        tf_novio = new javax.swing.JTextField();
        lab5 = new javax.swing.JLabel();
        tf_papa_novio = new javax.swing.JTextField();
        tf_mama_novio = new javax.swing.JTextField();
        lab6 = new javax.swing.JLabel();
        lab7 = new javax.swing.JLabel();
        tf_novia = new javax.swing.JTextField();
        lab9 = new javax.swing.JLabel();
        tf_papa_novia = new javax.swing.JTextField();
        lab10 = new javax.swing.JLabel();
        tf_mama_novia = new javax.swing.JTextField();
        lab11 = new javax.swing.JLabel();
        tf_proclamas = new javax.swing.JTextField();
        lab12 = new javax.swing.JLabel();
        tf_testigos = new javax.swing.JTextField();
        lab13 = new javax.swing.JLabel();
        lab14 = new javax.swing.JLabel();
        tf_rc_lugar = new javax.swing.JTextField();
        lab15 = new javax.swing.JLabel();
        tf_rc_año = new javax.swing.JTextField();
        lab16 = new javax.swing.JLabel();
        tf_rc_tomo = new javax.swing.JTextField();
        lab17 = new javax.swing.JLabel();
        tf_rc_acta = new javax.swing.JTextField();
        lab18 = new javax.swing.JLabel();
        tf_nota = new javax.swing.JTextField();
        lab19 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        lab20 = new javax.swing.JLabel();
        tf_rp_folio = new javax.swing.JTextField();
        lab21 = new javax.swing.JLabel();
        tf_rp_numero = new javax.swing.JTextField();
        lab22 = new javax.swing.JLabel();
        tf_rp_libro = new javax.swing.JTextField();
        tf_hijos = new javax.swing.JTextField();
        lis_autoridad = new javax.swing.JComboBox<>();
        lab23 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tf_novedades = new javax.swing.JTextArea();
        jButton5 = new javax.swing.JButton();
        lab24 = new javax.swing.JLabel();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setTitle("Ingreso de Matrimonio");
        setPreferredSize(new java.awt.Dimension(1000, 700));
        setSize(new java.awt.Dimension(1000, 700));

        lab2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lab2.setForeground(new java.awt.Color(0, 0, 204));
        lab2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lab2.setText("Fecha ");

        tf_fecha.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tf_fecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_fechaActionPerformed(evt);
            }
        });
        tf_fecha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tf_fechaKeyReleased(evt);
            }
        });

        lab3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lab3.setForeground(new java.awt.Color(0, 0, 204));
        lab3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lab3.setText("Nombre Sacerdote");

        tf_sacerdote.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tf_sacerdote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_sacerdoteActionPerformed(evt);
            }
        });

        lab4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lab4.setForeground(new java.awt.Color(0, 0, 204));
        lab4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lab4.setText("Nombre Novio");

        tf_novio.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tf_novio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_novioActionPerformed(evt);
            }
        });

        lab5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lab5.setForeground(new java.awt.Color(0, 0, 204));
        lab5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lab5.setText("Nombre Papa Novio");

        tf_papa_novio.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tf_papa_novio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_papa_novioActionPerformed(evt);
            }
        });

        tf_mama_novio.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tf_mama_novio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_mama_novioActionPerformed(evt);
            }
        });

        lab6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lab6.setForeground(new java.awt.Color(0, 0, 204));
        lab6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lab6.setText("Nombre Mama Novio");

        lab7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lab7.setForeground(new java.awt.Color(0, 0, 204));
        lab7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lab7.setText("Nombre Novia");

        tf_novia.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tf_novia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_noviaActionPerformed(evt);
            }
        });

        lab9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lab9.setForeground(new java.awt.Color(0, 0, 204));
        lab9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lab9.setText("Nombre Papa Novia");

        tf_papa_novia.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tf_papa_novia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_papa_noviaActionPerformed(evt);
            }
        });

        lab10.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lab10.setForeground(new java.awt.Color(0, 0, 204));
        lab10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lab10.setText("Nombre Mama Novia");

        tf_mama_novia.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tf_mama_novia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_mama_noviaActionPerformed(evt);
            }
        });

        lab11.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lab11.setForeground(new java.awt.Color(0, 0, 204));
        lab11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lab11.setText("Proclamas");

        tf_proclamas.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tf_proclamas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_proclamasActionPerformed(evt);
            }
        });

        lab12.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lab12.setForeground(new java.awt.Color(0, 0, 204));
        lab12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lab12.setText("Nombres Testigos");

        tf_testigos.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tf_testigos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_testigosActionPerformed(evt);
            }
        });

        lab13.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lab13.setForeground(new java.awt.Color(0, 0, 204));
        lab13.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lab13.setText("Registro Parroquial");

        lab14.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lab14.setForeground(new java.awt.Color(0, 0, 204));
        lab14.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lab14.setText("Lugar");

        tf_rc_lugar.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tf_rc_lugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_rc_lugarActionPerformed(evt);
            }
        });

        lab15.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lab15.setForeground(new java.awt.Color(0, 0, 204));
        lab15.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lab15.setText("Año");

        tf_rc_año.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tf_rc_año.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_rc_añoActionPerformed(evt);
            }
        });
        tf_rc_año.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tf_rc_añoKeyReleased(evt);
            }
        });

        lab16.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lab16.setForeground(new java.awt.Color(0, 0, 204));
        lab16.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lab16.setText("Tomo");

        tf_rc_tomo.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tf_rc_tomo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_rc_tomoActionPerformed(evt);
            }
        });

        lab17.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lab17.setForeground(new java.awt.Color(0, 0, 204));
        lab17.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lab17.setText("Acta");

        tf_rc_acta.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tf_rc_acta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_rc_actaActionPerformed(evt);
            }
        });

        lab18.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lab18.setForeground(new java.awt.Color(0, 0, 204));
        lab18.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lab18.setText("Nota Marginal");

        tf_nota.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tf_nota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_notaActionPerformed(evt);
            }
        });

        lab19.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lab19.setForeground(new java.awt.Color(0, 0, 204));
        lab19.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lab19.setText("Legitimacion de Hijos");

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 0, 255));
        jButton2.setText("Ingresar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 0, 255));
        jButton3.setText("Salir");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        lab20.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lab20.setForeground(new java.awt.Color(0, 0, 204));
        lab20.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lab20.setText("Numero");

        tf_rp_folio.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tf_rp_folio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_rp_folioActionPerformed(evt);
            }
        });

        lab21.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lab21.setForeground(new java.awt.Color(0, 0, 204));
        lab21.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lab21.setText("Folio/Pagina");

        tf_rp_numero.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tf_rp_numero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_rp_numeroActionPerformed(evt);
            }
        });

        lab22.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lab22.setForeground(new java.awt.Color(0, 0, 204));
        lab22.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lab22.setText("Libro");

        tf_rp_libro.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tf_rp_libro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_rp_libroActionPerformed(evt);
            }
        });

        tf_hijos.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tf_hijos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_hijosActionPerformed(evt);
            }
        });

        lis_autoridad.setMinimumSize(new java.awt.Dimension(28, 23));
        lis_autoridad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lis_autoridadActionPerformed(evt);
            }
        });

        lab23.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lab23.setForeground(new java.awt.Color(0, 0, 204));
        lab23.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lab23.setText("Novedades");

        tf_novedades.setColumns(20);
        tf_novedades.setRows(5);
        jScrollPane2.setViewportView(tf_novedades);

        jButton5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(0, 0, 255));
        jButton5.setText("Limpiar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        lab24.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lab24.setForeground(new java.awt.Color(0, 0, 204));
        lab24.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lab24.setText("Registro Civil");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lab24, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lab19, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lab18, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(38, 38, 38)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(tf_hijos, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tf_nota, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lab23, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 486, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lab21)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(tf_rp_folio, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(lab20, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(tf_rp_numero, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(25, 25, 25)
                                    .addComponent(lab22, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(tf_rp_libro, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(lab14, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(33, 33, 33)
                                            .addComponent(tf_rc_lugar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(lab15, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(29, 29, 29)
                                            .addComponent(tf_rc_año, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(27, 27, 27)
                                            .addComponent(lab16)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(tf_rc_tomo, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(lab13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(40, 40, 40)
                                    .addComponent(lab17, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(tf_rc_acta, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(lab12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lab10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lab9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lab7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lab6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lab5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lab4, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lab2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(lab3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lab11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(2, 2, 2)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(tf_sacerdote, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lis_autoridad, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(tf_proclamas)
                                    .addComponent(tf_novio)
                                    .addComponent(tf_papa_novio)
                                    .addComponent(tf_mama_novio)
                                    .addComponent(tf_novia)
                                    .addComponent(tf_papa_novia)
                                    .addComponent(tf_mama_novia)
                                    .addComponent(tf_testigos, javax.swing.GroupLayout.PREFERRED_SIZE, 556, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tf_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(268, 268, 268)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(298, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lab2)
                    .addComponent(tf_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tf_sacerdote, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lab3)
                        .addComponent(lis_autoridad, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lab11)
                    .addComponent(tf_proclamas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_novio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lab4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lab5)
                    .addComponent(tf_papa_novio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lab6)
                    .addComponent(tf_mama_novio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lab7)
                    .addComponent(tf_novia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lab9)
                    .addComponent(tf_papa_novia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lab10)
                    .addComponent(tf_mama_novia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lab12)
                    .addComponent(tf_testigos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lab24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lab14)
                    .addComponent(tf_rc_lugar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lab15)
                    .addComponent(tf_rc_año, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lab16)
                    .addComponent(tf_rc_tomo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lab17)
                    .addComponent(tf_rc_acta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lab13)
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lab20)
                    .addComponent(lab22)
                    .addComponent(tf_rp_libro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_rp_numero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lab21)
                    .addComponent(tf_rp_folio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lab18)
                    .addComponent(tf_nota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lab19)
                    .addComponent(tf_hijos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lab23)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                        .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)))
                .addGap(139, 139, 139))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tf_fechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_fechaActionPerformed
        tf_sacerdote.requestFocusInWindow();
    }//GEN-LAST:event_tf_fechaActionPerformed

    private void tf_sacerdoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_sacerdoteActionPerformed
        tf_proclamas.requestFocusInWindow();
    }//GEN-LAST:event_tf_sacerdoteActionPerformed

    private void tf_novioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_novioActionPerformed
        tf_papa_novio.requestFocusInWindow();
    }//GEN-LAST:event_tf_novioActionPerformed

    private void tf_papa_novioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_papa_novioActionPerformed
        tf_mama_novio.requestFocusInWindow();
    }//GEN-LAST:event_tf_papa_novioActionPerformed

    private void tf_mama_novioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_mama_novioActionPerformed
        tf_novia.requestFocusInWindow();
    }//GEN-LAST:event_tf_mama_novioActionPerformed

    private void tf_noviaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_noviaActionPerformed
       tf_papa_novia.requestFocusInWindow();        
    }//GEN-LAST:event_tf_noviaActionPerformed

    private void tf_papa_noviaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_papa_noviaActionPerformed
        tf_mama_novia.requestFocusInWindow();
    }//GEN-LAST:event_tf_papa_noviaActionPerformed

    private void tf_mama_noviaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_mama_noviaActionPerformed
        tf_testigos.requestFocusInWindow();
    }//GEN-LAST:event_tf_mama_noviaActionPerformed

    private void tf_proclamasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_proclamasActionPerformed
        tf_novio.requestFocusInWindow();
    }//GEN-LAST:event_tf_proclamasActionPerformed

    private void tf_testigosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_testigosActionPerformed
        tf_rc_lugar.requestFocusInWindow();
    }//GEN-LAST:event_tf_testigosActionPerformed

    private void tf_rc_lugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_rc_lugarActionPerformed
        tf_rc_año.requestFocusInWindow();
    }//GEN-LAST:event_tf_rc_lugarActionPerformed

    private void tf_rc_añoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_rc_añoActionPerformed
        tf_rc_tomo.requestFocusInWindow();
    }//GEN-LAST:event_tf_rc_añoActionPerformed

    private void tf_rc_tomoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_rc_tomoActionPerformed
        tf_rc_acta.requestFocusInWindow();
    }//GEN-LAST:event_tf_rc_tomoActionPerformed

    private void tf_rc_actaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_rc_actaActionPerformed
        tf_rp_folio.requestFocusInWindow();
    }//GEN-LAST:event_tf_rc_actaActionPerformed

    private void tf_notaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_notaActionPerformed
        tf_hijos.requestFocusInWindow();
    }//GEN-LAST:event_tf_notaActionPerformed
   
    public boolean valida_datos(){    
      if (tf_fecha.getText().isEmpty() || 
          tf_sacerdote.getText().isEmpty() || tf_novio.getText().isEmpty() || tf_novia.getText().isEmpty() ||
          tf_testigos.getText().isEmpty()  
              )
          return false;
      else 
          return true;
    }
    public void limpiar_datos(){
      setea_Fecha_actual(tf_fecha);
      tf_sacerdote.setText("");
      tf_proclamas.setText(""); tf_novio.setText(""); tf_papa_novio.setText(""); tf_mama_novio.setText("");
      tf_novia.setText(""); tf_papa_novia.setText(""); tf_mama_novia.setText("");
      tf_testigos.setText(""); tf_rc_lugar.setText("Guayaquil"); 
      tf_rc_año.setText(""); tf_rc_tomo.setText(""); tf_rc_acta.setText("");
      tf_rp_folio.setText(""); tf_rp_numero.setText("");  tf_rp_libro.setText("");
      tf_nota.setText(""); tf_hijos.setText(""); tf_novedades.setText("");
    }
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
                 
        String arst[] = new String[21];
        arst[0] = "";  arst[1] = tf_fecha.getText(); arst[2] = tf_sacerdote.getText(); 
        arst[3] = tf_proclamas.getText();  arst[4] = tf_novio.getText(); arst[5] = tf_papa_novio.getText();
        arst[6] = tf_mama_novio.getText();  arst[7] = tf_novia.getText(); arst[8] = tf_papa_novia.getText();
        arst[9] = tf_mama_novia.getText(); arst[10] = tf_testigos.getText(); arst[11] = tf_rc_lugar.getText();
        arst[12] = tf_rc_año.getText(); arst[13] = tf_rc_tomo.getText(); arst[14] = tf_rc_acta.getText();
        arst[15] = tf_nota.getText(); arst[16] = tf_hijos.getText();
        arst[17] = tf_rp_folio.getText(); arst[18] = tf_rp_numero.getText(); arst[19] = tf_rp_libro.getText();
        arst[20] = tf_novedades.getText();
        
        Connection conn = null;
        Statement   stm = null;
        
        boolean bo = valida_datos(); 
        if (!bo)  { 
            JOptionPane.showMessageDialog(null, "Usted debe llenar todos los datos Obligatorios ");
            return ; } 
        
        try 
        {   
            conn = obtiene_conexion();            
            stm = conn.createStatement();
            
            DateFormat formatter = new SimpleDateFormat("dd/MM/yyyy");
            Date d_fecha = formatter.parse(arst[1]);
            java.sql.Date dato_Fecha = new java.sql.Date(d_fecha.getTime());            
            
            String sql = " insert into matrimonios "
                    +    " (fecha_matri, nombre_sacerdote, proclamas,"
                    +    " nombre_novio, nombre_papa_novio, nombre_mama_novio, nombre_novia,"
                    +    " nombre_papa_novia, nombre_mama_novia, nombre_testigos, rc_lugar, "
                    +    " rc_año, rc_tomo, rc_acta, nota_marginal, legitimacion_de_hijos, "
                    +    " rp_folio, rp_numero, rp_libro, novedades)"
                    +    " values ( '"  + dato_Fecha + "', '" + arst[2] + "', '" + arst[3] + "', '" + arst[4] + "', '"  
                    +                   arst[5] + "', '" + arst[6] + "', '" + arst[7] + "', '" + arst[8] + "', '" + arst[9] + "', '"
                    +                   arst[10] + "', '" + arst[11] + "', '" + arst[12] + "', '" + arst[13] + "', '" + arst[14] + "', '" 
                    +                   arst[15] + "', '"  + arst[16] +  "', '" 
                    +                   arst[17] + "', '" + arst[18] + "', '" + arst[19] + "', '" + arst[20] + "') ";  
            System.out.println("sql " + sql);        
            stm.executeUpdate(sql);
            System.out.println("Insert completo.");
            JOptionPane.showMessageDialog(null, "Se realizo la insercion de datos correctamente");
            limpiar_datos();
            
        }
        catch(SQLException e) {                         
            System.out.println("Error SQLException al insertar datos " + e.getMessage() );
            JOptionPane.showMessageDialog(null, "Error SQLException al insertar datos " + e.getMessage() );
        }
        catch(Exception e){ 
            System.out.println("Error Exception al insertar datos " + e.getMessage() );
            JOptionPane.showMessageDialog(null, "Error Exception al insertar datos " + e.getMessage() );
        }
        finally {
            try {
                 if (conn != null) conn.close();
                 if (stm != null) stm.close();
            }
            catch(SQLException sq){
              System.out.println("Error en Finally, cerrando objeto conexion al insertar datos " + sq.getMessage() );
              JOptionPane.showMessageDialog(null, "Error en Finally, cerrando conexion al insertar datos " + sq.getMessage() );
            }       
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        //System.exit(0);
        this.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void tf_fechaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_fechaKeyReleased
        if (tf_fecha.getText().length() > 10) {
               tf_fecha.setText("");
               setea_Fecha_actual(tf_fecha);
        }
    }//GEN-LAST:event_tf_fechaKeyReleased

    private void tf_rc_añoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_rc_añoKeyReleased
        if (tf_rc_año.getText().length() > 4) {
               tf_rc_año.setText("");
              
        }
    }//GEN-LAST:event_tf_rc_añoKeyReleased

    private void tf_rp_folioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_rp_folioActionPerformed
        tf_rp_numero.requestFocusInWindow();
    }//GEN-LAST:event_tf_rp_folioActionPerformed

    private void tf_rp_numeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_rp_numeroActionPerformed
        tf_rp_libro.requestFocusInWindow();
    }//GEN-LAST:event_tf_rp_numeroActionPerformed

    private void tf_rp_libroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_rp_libroActionPerformed
        tf_nota.requestFocusInWindow();
    }//GEN-LAST:event_tf_rp_libroActionPerformed

    private void tf_hijosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_hijosActionPerformed
        tf_novedades.requestFocusInWindow();
    }//GEN-LAST:event_tf_hijosActionPerformed

    private void lis_autoridadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lis_autoridadActionPerformed

        String ini = lis_autoridad.getSelectedItem().toString();
        tf_sacerdote.setText(ini);
    }//GEN-LAST:event_lis_autoridadActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        limpiar_datos();
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(gui_Matri_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(gui_Matri_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(gui_Matri_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(gui_Matri_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new gui_Matri_Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lab10;
    private javax.swing.JLabel lab11;
    private javax.swing.JLabel lab12;
    private javax.swing.JLabel lab13;
    private javax.swing.JLabel lab14;
    private javax.swing.JLabel lab15;
    private javax.swing.JLabel lab16;
    private javax.swing.JLabel lab17;
    private javax.swing.JLabel lab18;
    private javax.swing.JLabel lab19;
    private javax.swing.JLabel lab2;
    private javax.swing.JLabel lab20;
    private javax.swing.JLabel lab21;
    private javax.swing.JLabel lab22;
    private javax.swing.JLabel lab23;
    private javax.swing.JLabel lab24;
    private javax.swing.JLabel lab3;
    private javax.swing.JLabel lab4;
    private javax.swing.JLabel lab5;
    private javax.swing.JLabel lab6;
    private javax.swing.JLabel lab7;
    private javax.swing.JLabel lab9;
    private javax.swing.JComboBox<String> lis_autoridad;
    private javax.swing.JTextField tf_fecha;
    private javax.swing.JTextField tf_hijos;
    private javax.swing.JTextField tf_mama_novia;
    private javax.swing.JTextField tf_mama_novio;
    private javax.swing.JTextField tf_nota;
    private javax.swing.JTextArea tf_novedades;
    private javax.swing.JTextField tf_novia;
    private javax.swing.JTextField tf_novio;
    private javax.swing.JTextField tf_papa_novia;
    private javax.swing.JTextField tf_papa_novio;
    private javax.swing.JTextField tf_proclamas;
    private javax.swing.JTextField tf_rc_acta;
    private javax.swing.JTextField tf_rc_año;
    private javax.swing.JTextField tf_rc_lugar;
    private javax.swing.JTextField tf_rc_tomo;
    private javax.swing.JTextField tf_rp_folio;
    private javax.swing.JTextField tf_rp_libro;
    private javax.swing.JTextField tf_rp_numero;
    private javax.swing.JTextField tf_sacerdote;
    private javax.swing.JTextField tf_testigos;
    // End of variables declaration//GEN-END:variables
}
