/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


package com.iglesia.matrimonios;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import org.apache.commons.logging.LogFactory; 
import net.sf.jasperreports.view.JasperViewer;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JasperPrintManager;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.util.Properties;

//import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.JButton;
//import java.awt.*;
import java.sql.Statement;
import java.sql.ResultSet;

public class gui_Matri_Consulta extends javax.swing.JFrame {

    /**
     * Creates new form gui_Matri_Consulta
     */
    String p_parroco = "";
    String p_ministro = "";
    String p_autoridad = "";
    String p_nombre_autoridad = "";
    
    public gui_Matri_Consulta() {
        initComponents();
        llena_combo();
        this.setLocationRelativeTo(null);
    }
    public Connection obtiene_conexion(){
        Connection con= null;
        try {
            String url = "jdbc:MySQL://localhost:3306/sacramentos";         //db is the name of the database
            String user = "root";
            String password = "";
            Class.forName("com.mysql.cj.jdbc.Driver");
            //System.out.println("error tipo A ");
            con = (Connection) DriverManager.getConnection(url,user,password);
            
        }            
        catch(SQLException e) {
                System.out.println("error tipo SQLException " + e.getMessage() );
                JOptionPane.showMessageDialog(null, "Error SqlException en Obtiene Conexion " + e.getMessage());
            }
        catch(Exception e){
                System.out.println("error tipo Exception " + e.getMessage() );
                JOptionPane.showMessageDialog(null, "Error Exception en Obtiene Conexion" + e.getMessage() );
            } 
        return con;
        }
    
    public void llena_combo(){
      Connection cnt = null;    
      Statement stm = null;
      try
        {    
            cnt = obtiene_conexion();
            stm = cnt.createStatement();
            String sql = "select * from opciones_autoridades";
            ResultSet rs = stm.executeQuery(sql);
            while ( rs.next() ){
              String str = rs.getString("desc_opc_aut") + ": " + rs.getString("nom_opc_autoridad");
              lis_autoridad.removeAll();
              lis_autoridad.addItem(str);
            }
      
        }
        catch(SQLException e) {
                System.out.println("error tipo SQLException " + e.getMessage() );
                JOptionPane.showMessageDialog(null, "Error SQLException en funcion llena_combo " + e.getMessage());
        }
        catch(Exception e){
                System.out.println("error tipo Exception " + e.getMessage() );
                JOptionPane.showMessageDialog(null, "Error Exception en funcion llena_combo " + e.getMessage());
        } 
        finally{
                try {   if (cnt != null)   cnt.close(); 
                        if (stm != null)   stm.close(); }
                catch(SQLException sq){
                    System.out.println("En Finally cerrando conexion en funcion llena_combo" + sq.getMessage() );
                    JOptionPane.showMessageDialog(null, "En Finally cerrando conexion, en funcion llena_combo " + sq.getMessage() );
                }
        }
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lab1 = new javax.swing.JLabel();
        jb_Consulta = new javax.swing.JButton();
        jb_Salir = new javax.swing.JButton();
        lab2 = new javax.swing.JLabel();
        lis_autoridad = new javax.swing.JComboBox<>();
        tf_nombre_casado = new javax.swing.JTextField();
        lab3 = new javax.swing.JLabel();
        tf_nombre_esposa = new javax.swing.JTextField();

        setTitle("Consulta de Matrimonio");

        lab1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lab1.setForeground(new java.awt.Color(0, 0, 204));
        lab1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lab1.setText("Nombre Esposo");

        jb_Consulta.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jb_Consulta.setForeground(new java.awt.Color(0, 0, 255));
        jb_Consulta.setText("Consultar");
        jb_Consulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_ConsultaActionPerformed(evt);
            }
        });

        jb_Salir.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jb_Salir.setForeground(new java.awt.Color(0, 0, 255));
        jb_Salir.setText("Salir");
        jb_Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_SalirActionPerformed(evt);
            }
        });

        lab2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lab2.setForeground(new java.awt.Color(0, 0, 204));
        lab2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lab2.setText("Autoridad que Firma");

        lis_autoridad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lis_autoridadActionPerformed(evt);
            }
        });

        tf_nombre_casado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_nombre_casadoActionPerformed(evt);
            }
        });

        lab3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lab3.setForeground(new java.awt.Color(0, 0, 204));
        lab3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lab3.setText("Nombre Esposa");

        tf_nombre_esposa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_nombre_esposaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lab1, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(tf_nombre_casado, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lab2)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jb_Consulta, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(jb_Salir, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(lis_autoridad, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lab3, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tf_nombre_esposa, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(50, 50, 50))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lab1)
                    .addComponent(tf_nombre_casado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lab3)
                    .addComponent(tf_nombre_esposa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lab2)
                    .addComponent(lis_autoridad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_Consulta, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_Salir, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(90, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jb_ConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_ConsultaActionPerformed

        String parametro = tf_nombre_casado.getText();
        Connection conn= null;
        // Conexion
        try {
            
            conn = obtiene_conexion();
            Map<String, Object> map = new HashMap<String, Object>();
            map.put("P_Nombre", tf_nombre_casado.getText()  );
            map.put("P_Nombre_Esposa", tf_nombre_esposa.getText()  );
            
            map.put("P_Autoridad", p_autoridad);
            map.put("P_Nombre_Autoridad", p_nombre_autoridad);
            
            System.out.println("paso 1" );
            String sep = System.getProperty("file.separator");
            //String ruta = "c:"+sep+"Users"+sep+ "pnsde"+sep+ "JaspersoftWorkspace"+sep+"MyReports"+sep+"simple.jasper";
            String ruta = "c:\\Users\\pnsde\\JaspersoftWorkspace\\MyReports\\PRODUCCION\\reporte_consulta_matrimonio.jasper";
            //sruta = ruta.replace("\\", "/");

                JasperReport jr = null;
                jr = (JasperReport) JRLoader.loadObjectFromFile(ruta);
                System.out.println("paso 2" );
                JasperPrint jp = JasperFillManager.fillReport( jr, map, conn);
                System.out.println("paso 3" );
                JasperViewer jv = new JasperViewer(jp);
                System.out.println("paso 4" );
                jv.setVisible(true);
                //JasperPrintManager.printReport(jp, true);
                System.out.println("paso 5" );

            }
            catch (JRException jrex) {
                System.out.println(jrex.toString());
                JOptionPane.showMessageDialog(null, "Error JRException en llamada al reporte " + jrex.getMessage());
            }
            catch(Exception e){
                System.out.println("error tipo Exception " + e.getMessage() );
                JOptionPane.showMessageDialog(null, "Error Exception en llamada al reporte > " + e.getMessage() );
            }
            finally{
                try {
                    if (conn != null)  conn.close();
                }
                catch(SQLException sq){
                    System.out.println("En Finally cerrando conexion en llamada al reporte " + sq.getMessage() );
                }
            }

    }//GEN-LAST:event_jb_ConsultaActionPerformed

    private void jb_SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_SalirActionPerformed
        //System.exit(0);
      this.setVisible(false);
    }//GEN-LAST:event_jb_SalirActionPerformed

    private void lis_autoridadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lis_autoridadActionPerformed
        
        String ini = lis_autoridad.getSelectedItem().toString();
        int pos = ini.indexOf(":");
        p_autoridad = ini.substring(0, pos);
        p_nombre_autoridad = ini.substring(pos+2);
        System.out.println(p_autoridad);
        System.out.println(p_nombre_autoridad);
        
        
    }//GEN-LAST:event_lis_autoridadActionPerformed

    private void tf_nombre_esposaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_nombre_esposaActionPerformed
        tf_nombre_casado.requestFocusInWindow();
    }//GEN-LAST:event_tf_nombre_esposaActionPerformed

    private void tf_nombre_casadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_nombre_casadoActionPerformed
        tf_nombre_esposa.requestFocusInWindow();
    }//GEN-LAST:event_tf_nombre_casadoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(gui_Matri_Consulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(gui_Matri_Consulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(gui_Matri_Consulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(gui_Matri_Consulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new gui_Matri_Consulta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jb_Consulta;
    private javax.swing.JButton jb_Salir;
    private javax.swing.JLabel lab1;
    private javax.swing.JLabel lab2;
    private javax.swing.JLabel lab3;
    private javax.swing.JComboBox<String> lis_autoridad;
    private javax.swing.JTextField tf_nombre_casado;
    private javax.swing.JTextField tf_nombre_esposa;
    // End of variables declaration//GEN-END:variables
}
